const actionTypes = {
    //USER
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILDED: "ADD_USER_FAILDED",

    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILDED: "DELETE_USER_FAILDED",

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILDED: 'USER_LOGIN_FAILDED',

    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILDED: 'USER_LOGOUT_FAILDED',

    GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
    GET_ALL_USER_FAILDED: "GET_ALL_USER_FAILDED",



    //Product
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILDED: "ADD_PRODUCT_FAILDED",

    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAILDED: "GET_ALL_PRODUCT_FAILDED",
}

export default actionTypes;