const actionTypes = {
    //USER
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILDED: "ADD_USER_FAILDED",

    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILDED: "DELETE_USER_FAILDED",

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILDED: 'USER_LOGIN_FAILDED',

    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILDED: 'USER_LOGOUT_FAILDED',

    GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
    GET_ALL_USER_FAILDED: "GET_ALL_USER_FAILDED",

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',



    //Product
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILDED: "ADD_PRODUCT_FAILDED",

    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAILDED: "GET_ALL_PRODUCT_FAILDED",

    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAILDED: "EDIT_PRODUCT_FAILDED",

    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAILDED: "DELETE_PRODUCT_FAILDED",

    GET_DETAIL_SUCCESS: "GET_DETAIL_SUCCESS",
    GET_DETAIL_FAILDED: "GET_DETAIL_FAILDED",

    GET_NAME_SUCCESS: "GET_NAME_SUCCESS",
    GET_NAME_FAILDED: "GET_NAME_FAILDED",


    //AllCode
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAILDED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',

    FETCH_BRAND_SUCCESS: 'FETCH_BRAND_SUCCESS',
    FETCH_BRAND_FAILDED: 'FETCH_BRAND_FAILDED',

    FETCH_SIZE_SUCCESS: 'FETCH_SIZE_SUCCESS',
    FETCH_SIZE_FAILDED: 'FETCH_SIZE_FAILDED',

    FETCH_COLOR_SUCCESS: 'FETCH_COLOR_SUCCESS',
    FETCH_COLOR_FAILDED: 'FETCH_COLOR_FAILDED',

    FETCH_STATUS_SUCCESS: 'FETCH_STATUS_SUCCESS',
    FETCH_STATUS_FAILDED: 'FETCH_STATUS_FAILDED',

    //Cart
    ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
    ADD_CART_FAILDED: 'ADD_CART_FAILDED',

    CLEAR_CART_SUCCESS: 'CLEAR_CART_SUCCESS',

    //Order
    GET_LIST_ORDER_SUCCESS: 'GET_LIST_ORDER_SUCCESS',
    GET_LIST_ORDER_FAILDED: 'GET_LIST_ORDER_FAILDED'

}

export default actionTypes;